import { z } from "zod";

export const workoutSchema = z.object({
  workoutId: z.number().int().positive().optional(), // workoutId is typically generated by the database
  templateId: z.number().int().positive().nullable().optional(), // templateId can be null
  name: z.string().nullable().optional(), // name can be null
  startTime: z.date().optional(), // startTime defaults in the database
  endTime: z.date().nullable().optional(), // endTime can be null
  durationSeconds: z.number().int().positive().nullable().optional(), // durationSeconds can be null
  totalVolumeKg: z.number().nullable().optional(), // totalVolumeKg can be null
  prsAchieved: z.number().int().min(0).optional(), // prsAchieved defaults in the database
});

export type Workout = z.infer<typeof workoutSchema>;
